//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NanoDataBase.Nanopool
{

    public partial class Balance : XPLiteObject
    {
        long fId;
        [Key]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        double fVolume;
        [DevExpress.Xpo.DisplayName(@"Объем")]
        public double Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<double>("Volume", ref fVolume, value); }
        }
        DateTime fDate;
        [DevExpress.Xpo.DisplayName(@"Время")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
    }

}
