//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NanoDataBase.Nanopool
{

    public partial class Balance : XPLiteObject
    {
        long fId;
        [Key]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        double fVolume;
        [DevExpress.Xpo.DisplayName(@"Объем")]
        public double Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<double>("Volume", ref fVolume, value); }
        }
        DateTime fDate;
        [DevExpress.Xpo.DisplayName(@"Время")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        double? fVolumeUsd;
        /// <summary>
        /// Объем сохраняется для истории по курсу на момент сохранения записи
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Объем в USD")]
        public double? VolumeUsd
        {
            get { return fVolumeUsd; }
            set { SetPropertyValue<double?>("VolumeUsd", ref fVolumeUsd, value); }
        }
        int fCurrencyType;
        /// <summary>
        /// Валюта храниться в Enum, а тут только её числовое значение.
        /// </summary>
        [DevExpress.Xpo.DisplayName(@"Валюта")]
        public int CurrencyType
        {
            get { return fCurrencyType; }
            set { SetPropertyValue<int>("CurrencyType", ref fCurrencyType, value); }
        }
    }

}
