//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace NanoDataBase.Nanopool
{

    [Persistent(@"ExchangeRate")]
    public partial class ExchangeRate : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        double fRate;
        public double Rate
        {
            get { return fRate; }
            set { SetPropertyValue<double>("Rate", ref fRate, value); }
        }
        RelationCurrency fCurrencyPair;
        [Association(@"ExchangeRateReferencesRelationCurrency")]
        public RelationCurrency CurrencyPair
        {
            get { return fCurrencyPair; }
            set { SetPropertyValue<RelationCurrency>("CurrencyPair", ref fCurrencyPair, value); }
        }
    }

}
